

TRUNCATE TABLE sous_type_mission RESTART IDENTITY CASCADE;



TRUNCATE TABLE choix_banque RESTART IDENTITY CASCADE;
TRUNCATE TABLE tranche_facture RESTART IDENTITY CASCADE;
TRUNCATE TABLE choix_banque RESTART IDENTITY CASCADE;
TRUNCATE TABLE choix_banque RESTART IDENTITY CASCADE;
TRUNCATE TABLE choix_banque RESTART IDENTITY CASCADE;
TRUNCATE TABLE choix_banque RESTART IDENTITY CASCADE;
