
TRUNCATE TABLE choix_banque RESTART IDENTITY CASCADE;
TRUNCATE TABLE tranche_facture RESTART IDENTITY CASCADE;
TRUNCATE TABLE facture RESTART IDENTITY CASCADE;
TRUNCATE TABLE budget RESTART IDENTITY CASCADE;
TRUNCATE TABLE equipe RESTART IDENTITY CASCADE;
TRUNCATE TABLE get_date RESTART IDENTITY CASCADE;
TRUNCATE TABLE chantier RESTART IDENTITY CASCADE;